# Generated by Django 6.0.3 on 2026-04-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='reqular_holiday',
            new_name='regular_holiday',
        ),
    ]
