# Generated by Django 6.0.3 on 2026-04-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
